### PR TITLE
Fixing tons of issues on the API wrapper.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by whopiyush** [comment]
Ill Merge This When I Get On Ma PC!

**Comment by whopiyush** [comment]
For Now I Dont think that not merging this will make a problem! Ill Merge Tommorow! Thanks

**Comment by ghost** [comment]
Why what is the issue??

**Comment by ghost** [comment]
@ionadev Already just now pushed a change for the version so it will work when you merge it.

**Comment by whopiyush** [comment]
Well It should be pushed to master tbh

**Pull request merged**
